# Pandas

#*Pandas is a python library used for manipulation of data sets. It has functions for data analysis , manipulation and visulization*

In [39]:
import pandas as pd
import numpy as np
import random

In [40]:
se1 = pd.Series([10,20,30],index = ['x','y','z'])
se1

x    10
y    20
z    30
dtype: int64

In [41]:
type(se1)

pandas.core.series.Series

# DataFrame 

#*dataframe is a data structure that store the data in two dimensional form*

In [42]:
pd.DataFrame

pandas.core.frame.DataFrame

In [43]:
marks = np.arange(61,91)
print(marks)

[61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
 85 86 87 88 89 90]


In [52]:
marks = np.arange(61,91)
shuffle(marks)
marks = marks.reshape(6,5)
print(marks)

[[62 88 64 66 69]
 [90 74 75 79 78]
 [76 67 86 63 61]
 [72 65 87 71 80]
 [83 85 73 84 82]
 [77 81 68 89 70]]


In [53]:
name = ['shaina','yogita','divya','aditya','tanishq','harsh']
subject = ['hindi','english','physics','maths','bio']


In [59]:
grade = pd.DataFrame(data = marks,index = name,columns = subject)
grade

hindi  english  physics  maths  bio
shaina      62       88       64     66   69
yogita      90       74       75     79   78
divya       76       67       86     63   61
aditya      72       65       87     71   80
tanishq     83       85       73     84   82
harsh       77       81       68     89   70

In [58]:
grade.head(2)

hindi  english  physics  maths  bio
shaina     62       88       64     66   69
yogita     90       74       75     79   78

In [57]:
grade.tail(2)

hindi  english  physics  maths  bio
tanishq     83       85       73     84   82
harsh       77       81       68     89   70

In [60]:
grade.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, shaina to harsh
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   hindi    6 non-null      int32
 1   english  6 non-null      int32
 2   physics  6 non-null      int32
 3   maths    6 non-null      int32
 4   bio      6 non-null      int32
dtypes: int32(5)
memory usage: 168.0+ bytes


In [61]:
grade.describe()

hindi    english    physics      maths        bio
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   76.666667  76.666667  75.500000  75.333333  73.333333
std     9.542886   9.521905   9.354143  10.327956   8.041559
min    62.000000  65.000000  64.000000  63.000000  61.000000
25%    73.000000  68.750000  69.250000  67.250000  69.250000
50%    76.500000  77.500000  74.000000  75.000000  74.000000
75%    81.500000  84.000000  83.250000  82.750000  79.500000
max    90.000000  88.000000  87.000000  89.000000  82.000000

#*creating dataframe using dictionary*

In [62]:
dict = {
    'Name':['Shaina','Tanni','Nonu','Nitin'],
    'Roll_no':[1001,1002,1003,1004],
    'Age':[14,15,17,13]
}

In [65]:
students = pd.DataFrame(dict)
students

Name  Roll_no  Age
0  Shaina     1001   14
1   Tanni     1002   15
2    Nonu     1003   17
3   Nitin     1004   13