In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [5]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr.shape

(3, 4)

In [7]:
# accessing specific elements of 2d array - array[raws , columns]
arr[1,3]

8

In [6]:
arr[:,3]

array([ 4,  8, 12])

In [9]:
arr[:2,1:3]

array([[2, 3],
       [6, 7]])

In [14]:
# creating all 0s matrix
a = np.zeros((3,4),dtype = "int32")

In [15]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
#creating all ones matrix

In [18]:
b= np.ones((4,5),dtype="int32")
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
b[:,1:3] = 10

In [27]:
print(b)

[[10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [29]:
b[:2,3:5]=4

In [30]:
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [31]:
b[2:4,3:5]=5
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  5  5]
 [10 10 10  5  5]]


In [32]:
c = np.full(b.shape,99)

In [33]:
print(c)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [34]:
d = np.full_like(c,5)

In [35]:
print(d)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [38]:
n1 = np.ones((3,3),dtype ="int32")
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
n2 = np.full_like(n1,2)
print(n2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [40]:
n3 = n1+n2

In [41]:
print(n3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [42]:
n= n3*n2
print(n)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [43]:
#creating 3d-array

In [46]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [47]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
arr[0,1,1]

5

In [50]:
arr[1,1,2]

12

In [51]:
arr[1,0,1]

8

In [52]:
arr[0,:,1:3]

array([[2, 3],
       [5, 6]])

In [54]:
arr[:,:,1:3] = 10

In [55]:
print(arr)

[[[ 1 10 10]
  [ 4 10 10]]

 [[ 7 10 10]
  [10 10 10]]]


In [75]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
b=a.reshape(2,3,2)

In [76]:
print(b)

[[[ 1  2]
  [ 3 10]
  [10 10]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [62]:
# copying a array

In [77]:
x = a.copy()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [79]:
#copy v/s view
x[3:6] = 10

In [80]:
print(x)

[ 1  2  3 10 10 10  7  8  9 10 11 12]


In [81]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
y =a.view()

In [83]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [86]:
y[4:10]=9
print(y)

[ 1  2  3  4  9  9  9  9  9  9 11 12]


In [87]:
print(a)

[ 1  2  3  4  9  9  9  9  9  9 11 12]


In [89]:
# iterating array's elements
for i in a:
    print(i+3)

4
5
6
7
12
12
12
12
12
12
14
15


In [90]:
#iteration in 2-d array
b = a.reshape(4,3)

In [91]:
print(b)

[[ 1  2  3]
 [ 4  9  9]
 [ 9  9  9]
 [ 9 11 12]]


In [93]:
for i in b:
    print(i)

[1 2 3]
[4 9 9]
[9 9 9]
[ 9 11 12]


In [94]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [95]:
c = np.concatenate((a,b),axis = 0)

In [96]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [97]:
#joining 2-d array

In [98]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

In [103]:
z = np.concatenate((x,y),axis = 0)

In [104]:
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
w = np.concatenate((x,y),axis = 1)

In [102]:
print(w)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [117]:
#sorting an array
arr1 = np.array([3,4,5,6,7,1,22,64,20,11,55,23])

In [118]:
arr2 = np.sort(arr1)

In [119]:
print(arr2)

[ 1  3  4  5  6  7 11 20 22 23 55 64]


In [120]:
#sorting 2-d array


In [121]:
a = arr1.reshape(3,4)
print(a)

[[ 3  4  5  6]
 [ 7  1 22 64]
 [20 11 55 23]]


In [122]:
b = np.sort(a)
print(b)

[[ 3  4  5  6]
 [ 1  7 22 64]
 [11 20 23 55]]
