In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
# Creating array using tuple

In [7]:
arr1 = np.array((4,5,6,7,3))

In [8]:
arr1

array([4, 5, 6, 7, 3])

In [9]:
arr1.shape

(5,)

In [10]:
arr.shape

(5,)

In [11]:
type(arr1)

numpy.ndarray

In [12]:
#Accessing element of 1 d array

In [13]:
arr[0]

1

In [14]:
arr[-1]

5

In [15]:
#slicing 1-d array

In [16]:
arr[0:3]

array([1, 2, 3])

In [17]:
arr[-3:-1]

array([3, 4])

In [18]:
arr[:4]

array([1, 2, 3, 4])

In [19]:
arr[2:]

array([3, 4, 5])

In [20]:
marks = np.array([1,2,3,4,5,6,7,8])

In [21]:
marks[:4]

array([1, 2, 3, 4])

In [22]:
marks[4:]

array([5, 6, 7, 8])

In [23]:
marks[-4:-2]

array([5, 6])

## *creating 2-d array*

In [24]:
array = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
array.shape

(2, 4)

In [27]:
# creating 2-d array using tuple

In [28]:
arr2 = np.array(((1,2,3),(3,4,5)))

In [29]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
arr2.shape

(2, 3)

In [32]:
type(arr2)

numpy.ndarray

In [33]:
arr2[0][2]

3

In [40]:
arr2[-1:-2]

array([], shape=(0, 3), dtype=int32)

In [43]:
#slicing 2-d array
arr2[0:1,1:3]

array([[2, 3]])

In [ ]:
h