# random module

In [3]:
# numpy offers a random module to generate a random number

In [4]:
import numpy as np
from numpy import random

In [5]:
x = np.random.randint(100)
print(x)

80


## *generating array of random nummbers*

In [6]:
a = np.random.randint(100,size =5)
print(a)

[86 97 70 39 90]


In [7]:
# generating 2-d array using random module

In [8]:
p = random.randint(100,size = (3,4))
print(p)

[[11 57 99 11]
 [99 82 28 83]
 [79 94 10 95]]


In [9]:
# generating random float 
c = random.rand()
print(c)

0.37287839357419883


In [10]:
#generating random float
d = random.rand(5)
print(d)

[0.96067483 0.95395557 0.74937069 0.74126209 0.3007419 ]


In [11]:
# genrating 2-d float random array
float_array = random.rand(3,4)
print(float_array)

[[0.8629588  0.75761966 0.56190527 0.28035239]
 [0.56951456 0.7186699  0.05654216 0.2782779 ]
 [0.7623408  0.72190947 0.06024416 0.06449482]]


In [12]:
# selecting a random number from given array
rand_num = random.choice([2,4,56,7,8,9])
print(rand_num)

56


In [13]:
colors = ['red','green','purple','black','grey','brown','mahroon','indigo','pink']
select_color = random.choice(colors)
print(select_color)

black


In [14]:
security_breaches = np.array([[0,5,1],[0,2,0],[1,1,2],[2,2,1],[0,0,0]])
print(security_breaches)

[[0 5 1]
 [0 2 0]
 [1 1 2]
 [2 2 1]
 [0 0 0]]


In [15]:
print(security_breaches.sum(axis = 1))

[6 2 4 5 0]


In [16]:
print(security_breaches.sum(axis = 0))

[ 3 10  4]


In [17]:
print(security_breaches.min(axis = 1))


[0 0 1 1 0]


In [18]:
print(security_breaches.min(axis = 0))


[0 0 0]


In [19]:
# finding mean
print(security_breaches.mean(axis = 1))

[2.         0.66666667 1.33333333 1.66666667 0.        ]


In [20]:
print(security_breaches.sum(axis = 0,keepdims = True))

[[ 3 10  4]]


In [21]:
print(security_breaches.sum(axis = 1 , keepdims = True))

[[6]
 [2]
 [4]
 [5]
 [0]]


In [22]:
array = np.array([[1,2,3],[4,5,7]])
array*3

array([[ 3,  6,  9],
       [12, 15, 21]])

In [23]:
# multiplying and addition of two array
array_a = np.array([[1,2,3],[4,5,6]])
array_b = np.array([[0,1,0],[1,0,1]])
array_a + array_b
array_a*array_b

array([[0, 2, 0],
       [4, 0, 6]])

In [24]:
array = np.array([[1,2,3],[4,5,6]])
array >2

array([[False, False,  True],
       [ True,  True,  True]])

In [25]:
array = np.array(["shaina" ,"is" ,"awesome"])
len(array)>2

True

In [26]:
vectorized_len = np.vectorize(len)
vectorized_len(array)>2

array([ True, False,  True])